set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'altercation/vim-colors-solarized'
call vundle#end()
filetype plugin indent on 

syntax on
let g:solarized_termtrans=1
let g:solarized_termcolors=256

set background=dark
colorscheme solarized


highlight clear SignColumn

set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

set pastetoggle=<F2> "Paste without being smart




